name: Build and deploy Node.js app to Azure Web App - notsominapi

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'data/**'
      - 'sql/**'
      
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install production dependencies
        run: npm ci --production

      - name: Zip artifact for deployment (excluding unnecessary files)
        run: |
          zip -r release.zip . -x "node_modules/*" "data/*" "sql/*" ".git/*" ".github/*" "*.md" "*.log"
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'notsominapi'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_825DE35A7FBC4B85AF19F075D91B8ACA }}
          package: release.zip